name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1 

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build -r test_multiplication


  singularity:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Singularity
        run: |
          sudo apt-get update && sudo apt-get install -y wget build-essential libseccomp-dev pkg-config squashfs-tools cryptsetup
          sudo rm -r /usr/local/go
          export VERSION=1.13.15 OS=linux ARCH=amd64
          wget -O /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz https://dl.google.com/go/go${VERSION}.${OS}-${ARCH}.tar.gz
          sudo tar -C /usr/local -xzf /tmp/go${VERSION}.${OS}-${ARCH}.tar.gz
          echo 'export GOPATH=${HOME}/go' >> ~/.bashrc
          echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc
          source ~/.bashrc
          curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh

          sh -s -- -b $(go env GOPATH)/bin v1.21.0

          mkdir -p ${GOPATH}/src/github.com/sylabs
          cd ${GOPATH}/src/github.com/sylabs
          git clone https://github.com/sylabs/singularity.git
          cd singularity
          git checkout v3.6.3
          cd ${GOPATH}/src/github.com/sylabs/singularity
          ./mconfig
          cd ./builddir
          make
          sudo make install

          singularity version

      - name: Build Singularity image
        run: |
          sudo singularity build matrix_multiplication.sif test1.def