name: C++ CI

on: [push, pull_request]

jobs:

  singularity:
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

            
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      
      - name: Transfer output.txt and error.txt from cluster to runner
        run: |
          sshpass -p '${{ secrets.SSH_PRIVATE_KEY }}' scp -o StrictHostKeyChecking=no ${{ secrets.CLUSTER_USER }}:/g100/home/usertrain/${{ secrets.CLUSTER_ACCOUNT_USERNAME }}/output.txt ./output.txt
          sshpass -p '${{ secrets.SSH_PRIVATE_KEY }}' scp -o StrictHostKeyChecking=no ${{ secrets.CLUSTER_USER }}:/g100/home/usertrain/${{ secrets.CLUSTER_ACCOUNT_USERNAME }}/error.txt ./error.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ./output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: error
          path: ./error.txt
