name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1 

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build -r test_multiplication


  singularity:
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Build singularity container
        run: |
          singularity build --fakeroot matrix_multiplication.sif container_matrix.def
      
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      
      - name: Transfer image and job.sh to GALILEO100
        run: |
          sshpass -p '${{ secrets.SSH_PRIVATE_KEY }}' scp -o StrictHostKeyChecking=no matrix_multiplication.sif job.sh ${{ secrets.CLUSTER_USER }}:/g100/home/usertrain/${{ secrets.CLUSTER_ACCOUNT_USERNAME }}

      - name: Run job.sh
        run: |
          sshpass -p '${{ secrets.SSH_PRIVATE_KEY }}' ssh -o StrictHostKeyChecking=no ${{ secrets.CLUSTER_USER }} 'sbatch job.sh'

      - name: Transfer output.txt and error.txt from cluster to runner
        run: |
          sshpass -p '${{ secrets.SSH_PRIVATE_KEY }}' scp -o StrictHostKeyChecking=no ${{ secrets.CLUSTER_USER }}:/g100/home/usertrain/${{ secrets.CLUSTER_ACCOUNT_USERNAME }}/output.txt ./
          sshpass -p '${{ secrets.SSH_PRIVATE_KEY }}' scp -o StrictHostKeyChecking=no ${{ secrets.CLUSTER_USER }}:/g100/home/usertrain/${{ secrets.CLUSTER_ACCOUNT_USERNAME }}/error.txt ./

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: error
          path: error.txt
