name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y mpich libmpich-dev

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build -r test_multiplication


  singularity:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container

      - name: Build Singularity image
        run: |
          sudo singularity build matrix_multiplication.sif test1.def