name: C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1 

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Create build directory
      run: mkdir build

    - name: Run CMake
      run: cmake . -B build

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build -r test_multiplication


  singularity:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Run singularity container
        run: |
          singularity build --fakeroot matrix_multiplication.sif container_matrix.def
          singularity run instance://instance1
